### ISSUE TITLE
AED not showing up

### ISSUE THREAD

**Issue by jxpsert** [openstreetmap-polska/openaedmap-frontend#110]
Hi there! I've recently added [this](https://www.openstreetmap.org/node/10285213146) AED. However, it doesn't seem to be showing up on OpenAEDMap. Did I tag something incorrectly, or is this a bug on OpenAEDMap's side?

For reference - here's the location on [OpenAEDMap](https://openaedmap.org/#map=17/51.826612/5.867843)

**Comment by RicoElectrico** [comment]
There's a bug in [OpenAEDmap backend ](https://github.com/openstreetmap-polska/openaedmap-backend) regarding tile expiry logic in  I've uncovered it earlier.
Even though the AED is in the database, it's not in the vector tiles.
Another example: https://openaedmap.org/#node_id=10280822109&map=17/52.323665/21.098454

**Comment by jxpsert** [comment]
So, is there anything I can do about this, or should I just wait until a fix is implemented?

**Comment by RicoElectrico** [comment]
We have to wait, unfortunately.

**Comment by jxpsert** [comment]
Was this an issue with this tile, or all tiles? I've added some AED's in another town, but they don't show up either.

**Comment by ttomasz** [comment]
> Was this an issue with this tile, or all tiles? I've added some AED's in another town, but they don't show up either.

It was global problem. I fixed one bug. You can check back in about 12 hours to see if the AED shows up on the map.

**Comment by jxpsert** [comment]
Issue looks to be fixed!

**Comment by RicoElectrico** [comment]
The issue is still present. Updates are still lagging behind.
Example: https://www.openstreetmap.org/node/10300322009 and https://openaedmap.org/#map=18/51.641145/17.130598 (not visible as of writing this comment 2023-02-01 19:26 CET)

**Comment by Fizzie41** [comment]
Problem is still occurring.

Two that I added 3 weeks ago aren't yet appearing:
https://www.openstreetmap.org/node/10948443832
https://www.openstreetmap.org/node/10991230059

Both should be visible here: https://openaedmap.org/#map=14/-25.06627/148.25927. Other POIs that I added at the same time are visible, but not the AEDs.

**Comment by jxpsert** [comment]
Reopening this based on @Fizzie41 's comment. Why/how is this still an issue?

**Comment by starsep** [comment]
I believe the issue is in the processing on the backend. We don't know where exactly

**Comment by Fizzie41** [comment]
Yes, there must be a problem somewhere? I've just tried a OT search for AEDs in Australia https://overpass-turbo.eu/s/1xkM which shows 258 of them, where you only have 244. For New Zealand, OT has 116 https://overpass-turbo.eu/s/1xkN vs 91. https://openaedmap.org/#map=3/-26.79/145

**Comment by rbovard** [comment]
I can also confirm the problem: the defibrillators I've been adding for a month now no longer appear, whereas before they were visible in less than a day.

**Comment by Fizzie41** [comment]
Thanks! Good to see that we helped find a hidden problem!

**Comment by starsep** [comment]
This issue has been resolved by new backend.
Thanks @Zaczero for great work! :rocket:

**Comment by rbovard** [comment]
Great, thanks a lot!

**Comment by Fizzie41** [comment]
Thanks for fixing this, but a further question, thanks.

Existing AEDs show at zoom 6: https://openaedmap.org/#map=6/-26.162/151.623 , but the two I added don't appear till zoom 7: https://openaedmap.org/#map=7/-25.881/150.788 ?

Shouldn't they all appear at the same zoom level?

**Comment by Zaczero** [comment]
> Thanks for fixing this, but a further question, thanks.
> 
> Existing AEDs show at zoom 6: https://openaedmap.org/#map=6/-26.162/151.623 , but the two I added don't appear till zoom 7: https://openaedmap.org/#map=7/-25.881/150.788 ?
> 
> Shouldn't they all appear at the same zoom level?

This displays properly for me. There can be up to 3 minutes cache difference on zoom levels >=6. I have also just deployed a new update which required ~30 mins maintenance during which tiles stopped updating. Maybe that's when you noticed this bug.

**Comment by Fizzie41** [comment]
Thanks!

I had just cleared my cache when I saw that they weren't displaying at all, so that may be the issue.

I'll check it again later & report back.
